"""Made a master Character table

Revision ID: 05729473d104
Revises: 9c1a6099ac2b
Create Date: 2024-11-06 11:08:38.412371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '05729473d104'
down_revision: Union[str, None] = '9c1a6099ac2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bab_progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progression_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bab_progressions_id'), 'bab_progressions', ['id'], unique=False)
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('character_class_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('weapon_id', sa.Integer(), nullable=True),
    sa.Column('spell_id', sa.Integer(), nullable=True),
    sa.Column('feat_id', sa.Integer(), nullable=True),
    sa.Column('armor_id', sa.Integer(), nullable=True),
    sa.Column('caster_type_id', sa.Integer(), nullable=True),
    sa.Column('money_value_id', sa.Integer(), nullable=True),
    sa.Column('racial_trait_id', sa.Integer(), nullable=True),
    sa.Column('saving_throw_progression_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('stat_id', sa.Integer(), nullable=True),
    sa.Column('class_ability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['armor_id'], ['armor.id'], ),
    sa.ForeignKeyConstraint(['caster_type_id'], ['caster_types.id'], ),
    sa.ForeignKeyConstraint(['character_class_id'], ['character_classes.id'], ),
    sa.ForeignKeyConstraint(['class_ability_id'], ['class_abilities.id'], ),
    sa.ForeignKeyConstraint(['feat_id'], ['feats.id'], ),
    sa.ForeignKeyConstraint(['money_value_id'], ['money_values.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['racial_trait_id'], ['racial_traits.id'], ),
    sa.ForeignKeyConstraint(['saving_throw_progression_id'], ['saving_throw_progressions.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stats.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('caster_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character_classes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'level_requirement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_abilities', 'numeric_modifier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('class_abilities', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('saving_throw_progressions', 'progression_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saving_throw_progressions', 'progression_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'numeric_modifier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('class_abilities', 'level_requirement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_abilities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character_classes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('caster_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    op.drop_table('character')
    op.drop_index(op.f('ix_bab_progressions_id'), table_name='bab_progressions')
    op.drop_table('bab_progressions')
    # ### end Alembic commands ###
