"""Initial migration

Revision ID: 18c75b35e298
Revises: 
Create Date: 2024-11-04 14:10:06.609424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '18c75b35e298'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hit_die', sa.Integer(), nullable=True),
    sa.Column('base_attack_bonus', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('saving_throws', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_classes_id'), 'character_classes', ['id'], unique=False)
    op.create_index(op.f('ix_character_classes_name'), 'character_classes', ['name'], unique=True)
    op.create_table('class_abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['character_class_id'], ['character_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_abilities_id'), 'class_abilities', ['id'], unique=False)
    op.create_table('class_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_class_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['character_class_id'], ['character_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_levels_id'), 'class_levels', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_class_levels_id'), table_name='class_levels')
    op.drop_table('class_levels')
    op.drop_index(op.f('ix_class_abilities_id'), table_name='class_abilities')
    op.drop_table('class_abilities')
    op.drop_index(op.f('ix_character_classes_name'), table_name='character_classes')
    op.drop_index(op.f('ix_character_classes_id'), table_name='character_classes')
    op.drop_table('character_classes')
    # ### end Alembic commands ###
