"""Added skills

Revision ID: 1bf453a8375a
Revises: 18c75b35e298
Create Date: 2024-11-04 14:47:11.910598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1bf453a8375a'
down_revision: Union[str, None] = '18c75b35e298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('character_classes', sa.Column('skill_points', sa.Integer(), nullable=True))
    op.add_column('character_classes', sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_classes', 'skills')
    op.drop_column('character_classes', 'skill_points')
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sources_pkey')
    )
    
