"""Removed some stuff I didn't need

Revision ID: 4772eb0e1b3c
Revises: 3cc803a46eed
Create Date: 2024-11-06 13:44:32.022872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4772eb0e1b3c'
down_revision: Union[str, None] = '3cc803a46eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('alignments', sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('alignments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('caster_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'level_requirement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_abilities', 'numeric_modifier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('class_abilities', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('equipment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('equipment', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('feats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('languages', 'learned_by_races',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('saving_throw_progressions', 'progression_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saving_throw_progressions', 'progression_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('languages', 'learned_by_races',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('feats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('equipment', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('equipment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'numeric_modifier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('class_abilities', 'level_requirement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_abilities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('caster_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alignments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('alignments', 'abbreviation')