"""Added a few more tables to manage some data.

Revision ID: 4e5cc0b2c41c
Revises: 05729473d104
Create Date: 2024-11-06 11:54:08.741719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4e5cc0b2c41c'
down_revision: Union[str, None] = '05729473d104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alignments_id'), 'alignments', ['id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gold_value', sa.Float(), nullable=True),
    sa.Column('container', sa.Boolean(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numeric_modifier', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('learned_by_races', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.alter_column('caster_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('character', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('bab_id', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('equipment_id', sa.Integer(), nullable=True))
    op.alter_column('character', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'character', 'equipment', ['equipment_id'], ['id'])
    op.create_foreign_key(None, 'character', 'bab_progressions', ['bab_id'], ['id'])
    op.create_foreign_key(None, 'character', 'languages', ['language_id'], ['id'])
    op.alter_column('class_abilities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'level_requirement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_abilities', 'numeric_modifier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('class_abilities', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('saving_throw_progressions', 'progression_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saving_throw_progressions', 'progression_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'numeric_modifier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('class_abilities', 'level_requirement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_abilities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.alter_column('character', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('character', 'equipment_id')
    op.drop_column('character', 'bab_id')
    op.drop_column('character', 'language_id')
    op.alter_column('caster_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_alignments_id'), table_name='alignments')
    op.drop_table('alignments')
    # ### end Alembic commands ###
