"""Added foreign keys to Character

Revision ID: a348db3007a8
Revises: 4e5cc0b2c41c
Create Date: 2024-11-06 13:19:12.259622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a348db3007a8'
down_revision: Union[str, None] = '4e5cc0b2c41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alignments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('caster_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('character', sa.Column('alignment_id', sa.Integer(), nullable=True))
    op.alter_column('character', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'character', 'alignments', ['alignment_id'], ['id'])
    op.alter_column('class_abilities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'level_requirement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_abilities', 'numeric_modifier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('class_abilities', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('equipment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('equipment', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('feats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('languages', 'learned_by_races',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('saving_throw_progressions', 'progression_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saving_throw_progressions', 'progression_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('languages', 'learned_by_races',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('feats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('equipment', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('equipment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('class_abilities', 'numeric_modifier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('class_abilities', 'level_requirement',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('class_abilities', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.alter_column('character', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('character', 'alignment_id')
    op.alter_column('caster_types', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alignments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
